### ISSUE TITLE
QAF parallel execution

### ISSUE THREAD

**Issue by sohailabbasi** [qmetry/qaf#124]
With the upgrade version of QAF 2.1.12-RC1 we are not able to do parallel execution on multiple devices.

It is not creating multiple instances on browser for multiple scenarios and in mobile too it is not picking all available devices for scenarios.

We have tried with older version i.e.2.1.9 it is working fine.

Please provide inputs if any.

**Comment by cjayswal** [comment]
Will you please provide steps to reproduce?

**Comment by sohailabbasi** [comment]
Hi,

Please find steps to reproduce below –

·         In Application properties selenium.singletone=0 (or method instead of 0)

·         In Config.xml ‘parallel=methods’ and thread count also mentioned globally. Also providing platform name for device rather than device Id in order to refrain device restrictions for scenarios.

·         In Application global.datadriven.parallel=true

We are looking for parallel execution of data driven scenarios and we need to pass data parameters from excel file having multiple sheet. (i.e. multiple scenarios take multiple device and execute it in order to reduce execution time.)

Regards,
Sohail Abbasi | Software Engineer (Automation)
Infostretch Corporation (India) Pvt. Ltd. | (an ISO9001-2015 and 27001 certified company)
Pune, MH | 411057
[Infostretch]

**Comment by cjayswal** [comment]
Are you authoring test in java, bdd or kwd?

**Comment by sohailabbasi** [comment]
We authoring in BDD with QAF.

Regards,
Sohail Abbasi | Software Engineer (Automation)
Infostretch Corporation (India) Pvt. Ltd. | (an ISO9001-2015 and 27001 certified company)
Pune, MH | 411057
[Infostretch]

**Comment by infoneershalin** [comment]
Hi,

1. New TestNG version considers priority in parallel execution as well and picks up methods with same priority to execute in parallel.
 2. To execute scenarios written in BDD in same order as they are in .bdd file QAF assigns priority in ascending order to the scenario if priority is not given in Meta-Data of scenario.

Now these two things conflict with each other and hence parallel=mehtods is not working.

Also TestNG team is still identifying execution strategy with preserve-order, priority,class priority etc.

By the time TestNG finalizes the execution strategy and QAF gets refactored, I will suggest to add priority in scenario meta-data to resolve this.

so 
in each scenario's Meta-Data will look something like this 

`META-DATA: {"description":"Sample Test Scenario","groups":["SMOKE"],"priority":1}`

make sure priority value is same either its 1 or 1000(keep it in 1-999 range) or something else, for all the scenarios which you want to execute in parallel

**Comment by cjayswal** [comment]
Use 2.1.12-RC2

**Comment by panaeteadriana** [comment]
Trying to run methods or tests in parallel is not working. All the settings are correctly added.
the Qaf version is 2.1.14

I added 
selenium.singletone=methods
global.datadriven.parallel=true in application.properties.

in testng I used : verbose="1" parallel="tests" thread-count="2">

After each method the driver is closing.Caused by: 
**org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?**

remote.server=127.0.0.1
remote.port=4723
remote.url="http://127.0.0.1:4723/wd/hub/"
driver.class=io.appium.java_client.AppiumDriver<MobileElement>
driver.capabilities.platformName=iOS
#driver.capabilities.appActivity=com.deloittedigital.AlphaTest
driver.capabilities.app=App.app
driver.capabilities.deviceName=iPhone Simulator
driver.capabilities.automationName=XCUITest
driver.capabilities.useJSONSource=true
driver.capabilities.simpleIsVisibleCheck=true
driver.capabilities.noReset=true
driver.capabilities.nativeWebTap=true
driver.capabilities.newCommandTimeout=4000
driver.capabilities.autoLaunch=true
