### ISSUE TITLE
When setting a variable in getBundle().setProperty() in one Test Case is valid for other test case as well. What should we do for not getting this value in other scenarios.

### ISSUE THREAD

**Issue by manishKumarCTS** [qmetry/qaf#178]
### QAF Version
> 2.1.12

### Steps To Reproduce
    1. Set the property in a test case using getBundle().setProperty();
    2. Try to get it in another Test case.

### Expected behavior
We should not get the value which we have set in getBundle().setProperty() in other Test Cases.

### Actual behavior
Getting value in getBundle().getString() in another Test Case which we have set in getBundle().setProperty() in previous Test Cases.

### Is the issue reproducible on runner?

- [ ] QAS
- [X] Maven
- [ ] Gradle
- [] Ant
- [X] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Your description of expected behavior is confusing. Are you looking for property value set in one test in another case? in that case you need to set dependency properly, as per your description, your one test is dependent on another to set property. If the test which sets property didn't executed first.

For questions, clarifications or help please post in [users group](https://groups.google.com/forum/#!forum/qaf-users) instead of creating git issue.

**Comment by manishKumarCTS** [comment]
I am setting a value in first Test Case by using getBundle().setProperty() method.
When I try to get this value in second Test Case by using getBundle().getString() method I am able to get it.
But my expectation is I should not get this value in any other Test Cases.
(I don't want that value to be get in other Test Cases)
What should I do to avoid this kind of situation.
I hope this description will clear your doubts.

**Comment by amitbhoraniya** [comment]
Simple you can clear that property in TestNg listener.

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
