### ISSUE TITLE
Code template generation with Unimplemented steps

### ISSUE THREAD

**Issue by ShankarChoudhury** [qmetry/qaf#224]
### QAF Version
2.1.12

### Steps To Reproduce
    1.Create a sample scenario in a feature
    2.Implement step definitions for all steps in the scenario except for last two
    3.Run the scenario

### Expected behavior
Quantum should(preferably) provide code snippet for all the un-implemented steps

### Actual behavior
Code snippet is provided for only the first step in the sequence which does not have a corresponding step implementation. For the rest of the unimplemented steps, there is no code snippet.

### Is the issue reproducible on runner?
no
- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
Applicable for any scenario

**Comment by ShankarChoudhury** [comment]
Thanks Chirag, while running my tests with dryrun.mode=true, it gave the snippet for all the unimplemented steps(No execution as performed as expected)
However, when I set the dry.mode=false, it executed the scenario and gave code snippet for only the first step that was unimplemented. Is it possible to have the execution as well code snippet for all unimplemented steps at the same time?

**Comment by cjayswal** [comment]
It is possible but not practical, and hence not supporting. Ideally when you are executing your test you should be ready with the step implementation. Furthermore, consider the case of actual execution where the failed test takes few seconds more to calculate all unimplemented steps will impact overall execution time! That's why dry run feature is provided to ensure you have all steps implemented.

**Comment by ShankarChoudhury** [comment]
Thanks, it helps.
