### ISSUE TITLE
Whether QAF supports WiniumDriver to automate windows based applications? If so, How to set the host URL capability and Desktop options capability 

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#227]
### QAF Version: 2.1.13
> Note: only the latest version is supported

### Steps To Reproduce
    1. driver.name as WiniumDriver and updated the driver.class as winiumDriver class
    2. How to set the host URL capability and Desktop options capability at beforeInitialize method in listener
    3.

### Expected behavior
Should be able to initialize the driver

### Actual behavior
Unable to initialize the driver

### Is the issue reproducible on runner?

- [x] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Is there any specific reason you want to use WiniumDriver?
You should try using [windows driver](http://appium.io/docs/en/drivers/windows/) appium implementation.

**Comment by wildcat111** [comment]
Chirag, is there any documentation on how to implement Windows Driver in QAF?

**Comment by cjayswal** [comment]
It should be add required dependencies, set appropriate capabilities and start using it. 

Windows driver is appium implementation so you can use it like android or ios appium driver. You can refer [how to run native app on appium](https://qmetry.github.io/qaf/latest/how_to_run_on_native_app_on_appium.html). Refer driver specific [documentation](http://appium.io/docs/en/drivers/windows/#the-windows-driver) for set up and other driver specific requirements.

**Comment by wildcat111** [comment]
Thank you @cjayswal I was able to make this work.  Here are the properties that I set to make it work:
remote.server=127.0.0.1
remote.port=4723
driver.name=appiumDriver
appium.additional.capabilities = {'platformName':'Windows','deviceName':'WindowsPC','automationName':'Appium','app':'[_Your App Name]_', 'driverClass':'io.appium.java_client.windows.WindowsDriver'}

I used the Appium Server to run against instead of launching WinAppDriver directly.  And obviously you have to have the Appium Dependency in your project.
