### ISSUE TITLE
ava.lang.classcastexception: java.lang.integer cannot be cast to java.lang.charsequence

### ISSUE THREAD

**Issue by debNV9** [qmetry/qaf#279]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce

    1.  public void testcase(map<string, string> data){
  data.get("'X") 
}
    2.
    3.

### Actual behavior

Getting class cast exception error when trying to pull integer from the excel document in the test case in QAF data driven framework 

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Which version of QAF you are using? 

With **2.1.14** data provider returns objects instead of Strings. So if you want to provide number as string you should quote it in test data. For example: 
`abcd` is String, `123` is Number `"123"` is String, `123 abc` is String 

Alternate is, when you get data you can cast it in string, for example:
```
String value = data.get("key").toString();
String value = String.valueOf(data.get("key"));
```

If you don't want data as object, you can [intercept](https://qmetry.github.io/qaf/latest/javadoc/com/qmetry/qaf/automation/testng/dataprovider/QAFDataProviderIntercepter.html#intercept-com.qmetry.qaf.automation.step.client.TestNGScenario-org.testng.ITestContext-java.util.List- ) to converts object to string using [data-provider-intercepter](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#data-provider-intercepter).

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
