### ISSUE TITLE
Up-grading Maven Dependencies

### ISSUE THREAD

**Issue by Harshala-Bhadarge** [qmetry/qaf#375]
Hello,

This issue is about the Maven Dependencies.

While up-grading Maven Dependencies i.e., Selenium And Appium I/O dependencies Previous Selenium Dependency : 2.53.0
Upgraded Selenium Dependency : 3.0.1/3.141.59, Previous Appium Dependency :<version>5.0.4</version>
		Upgraded Appium Dependency : <version>7.3.0</version> 
			
, the other code is getting affected with few errors viz., 
1. Error at :1. import com.thoughtworks.selenium.SeleniumException; 
-----> The import com.thoughtworks.selenium cannot be resolved
                 2. import io.appium.java_client.android.AndroidKeyCode;
-----> The import io.appium.java_client.android.AndroidKeyCode cannot be resolved
                  import io.appium.java_client.android.Connection;
----->The import io.appium.java_client.android.Connection cannot be resolved
2. Selenium Exception
-----> SeleniumException cannot be resolved to a type
3. Error for Connection
4.  Error at Press and Tap Methods
-----> The method press(PointOption) in the type TouchAction is not applicable for the arguments (int, int)

Thanks!!!
Harshala B.

**Comment by cjayswal** [comment]
which version of qaf you are using? If the error is from your project code, you need to fix it. QAF latest version (3.0.0) works with selenium 3.x and appium latest versions. You can specify dependency/version in pom file.

It is recommended to post questions with details (your current configuration, relevant code, execution logs, etc) in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by vaibhav780** [comment]
We are using QAF 2.1.12 version in our code. 

For additional information, I have attached a pom file

Thanks
Vaibhav M.
[pom.txt](https://github.com/qmetry/qaf/files/7020963/pom.txt)

**Comment by cjayswal** [comment]
Use the latest version of selenium/appium and qaf. Instead of using [qaf-perfecto-support](https://github.com/qmetry/qaf-perfecto-support#qaf-perfecto-support) start using [Quantum](https://github.com/Project-Quantum/Quantum) library. [Quantum](https://github.com/Project-Quantum/Quantum) is replacement of this qaf-perfecto-support project. You may required code migration, refer [QAF release notes](https://qmetry.github.io/qaf/latest/release_notes.html) and [Quantum documentation](https://github.com/Perfecto-Quantum/Quantum-Starter-Kit#quantum-starter-kit).

**Comment by cjayswal** [comment]
closing inactive issue
